Clean up code (#628)
istio/operator pull request #629
Opened 2019-11-22 22:14 UTC by ostromart

* Clean up code

* Lint

2019-11-22 22:16 UTC, istio-testing commented
@ostromart: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
mandiff_operator_release-1.4 | 2e13ef00f25435909bd4b0529d12fc7cb31f8100 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_operator/629/mandiff_operator_release-1.4/154) | `/test mandiff_operator_release-1.4`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-22 22:16 UTC, istio-testing commented
@ostromart: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
mandiff_operator_release-1.4 | 2e13ef00f25435909bd4b0529d12fc7cb31f8100 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_operator/629/mandiff_operator_release-1.4/154) | `/test mandiff_operator_release-1.4`
mesh_operator_release-1.4 | 2e13ef00f25435909bd4b0529d12fc7cb31f8100 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_operator/629/mesh_operator_release-1.4/153) | `/test mesh_operator_release-1.4`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-22 22:16 UTC, istio-testing commented
@ostromart: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
mandiff_operator_release-1.4 | 2e13ef00f25435909bd4b0529d12fc7cb31f8100 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_operator/629/mandiff_operator_release-1.4/154) | `/test mandiff_operator_release-1.4`
mesh_operator_release-1.4 | 2e13ef00f25435909bd4b0529d12fc7cb31f8100 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_operator/629/mesh_operator_release-1.4/153) | `/test mesh_operator_release-1.4`
lint_operator_release-1.4 | 2e13ef00f25435909bd4b0529d12fc7cb31f8100 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_operator/629/lint_operator_release-1.4/155) | `/test lint_operator_release-1.4`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-22 22:18 UTC, istio-testing commented
@ostromart: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
mandiff_operator_release-1.4 | 2e13ef00f25435909bd4b0529d12fc7cb31f8100 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_operator/629/mandiff_operator_release-1.4/154) | `/test mandiff_operator_release-1.4`
mesh_operator_release-1.4 | 2e13ef00f25435909bd4b0529d12fc7cb31f8100 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_operator/629/mesh_operator_release-1.4/153) | `/test mesh_operator_release-1.4`
lint_operator_release-1.4 | 2e13ef00f25435909bd4b0529d12fc7cb31f8100 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_operator/629/lint_operator_release-1.4/155) | `/test lint_operator_release-1.4`
test_operator_release-1.4 | 2e13ef00f25435909bd4b0529d12fc7cb31f8100 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_operator/629/test_operator_release-1.4/155) | `/test test_operator_release-1.4`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-25 15:15 UTC, jwendell requested changes
`+1,567 −1,528`

Such a big change for just a "cleanup code"?
Could you please clarify what issue(s) this PR fixes?

2019-11-25 17:21 UTC, ostromart commented
All of these are just moves and documentation - the current location of the moved functions makes the code less readable since there are functions in packages that have nothing to do with the purpose of the package (e.g. yaml comparison in object manipulation package). I can answer any specifics about each move in the files.

2019-11-25 17:21 UTC, ostromart commented
btw. it's necessary to cherrypick this from master since without this future small cherrypicks will likely fail.

2019-11-25 19:32 UTC, jwendell approved these changes

2019-11-25 19:33 UTC, merged